id = "surface"
name = "Surface"
version = "0.0.1"
schema_version = 1
authors = ["42mon <42mon@users.noreply.github.com>"]
description = "Surface template language support for Zed"
repository = "https://github.com/42mon/zed-surface"

[grammars.surface]
# Local development source. Replace with the public repository URL before
# submitting the extension to the Zed registry.
repository = "file:///Users/42mon/Projects/sandbox/zed-surface"
rev = "e4a2c36ccbd543edc93bb3ca4e8deab2187b8c55"
path = "grammar"
