id = "surface"
name = "Surface"
version = "0.0.3"
schema_version = 1
authors = ["42mon <42mon@users.noreply.github.com>"]
description = "Surface template language support for Zed"
repository = "https://github.com/ebool/zed-surface"

[language_servers.surface-language-server]
name = "Surface Language Server"
languages = ["Surface"]

[language_servers.surface-language-server.language_ids]
Surface = "surface"

[grammars.surface]
repository = "https://github.com/ebool/zed-surface"
rev = "e4a2c36ccbd543edc93bb3ca4e8deab2187b8c55"
path = "grammar"
